# Generated by Django 4.2.1 on 2023-06-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cinema', '0004_alter_film_title_alter_screen_screen_number_showing'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='film_images/'),
        ),
    ]
